CREATE TABLE IF NOT EXISTS site_content (
  content_key TEXT PRIMARY KEY,
  content_value TEXT NOT NULL,
  max_chars INTEGER NOT NULL,
  page TEXT NOT NULL,
  section TEXT NOT NULL,
  element_type TEXT NOT NULL DEFAULT 'text'
);

INSERT OR IGNORE INTO site_content (content_key, content_value, max_chars, page, section, element_type) VALUES

('index.preloader.word', 'मौन', 10, 'index', 'preloader', 'word'),
('index.hero.subtext', 'Films', 20, 'index', 'hero', 'text'),
('index.hero.bottom', 'Stories for the Future.', 40, 'index', 'hero', 'text'),
('index.brand.subtext', 'Films • Ideas • Meaning', 40, 'index', 'brand', 'text'),

('about.marker', 'सृजन', 15, 'about', 'marker', 'devanagari'),
('about.hero.eyebrow', 'Intent Statement', 30, 'about', 'hero', 'eyebrow'),
('about.hero.title', 'Story first. Always.', 50, 'about', 'hero', 'title'),
('about.hero.lead', 'We are a film-first creative studio rooted in storytelling, culture, and intent. Whether the form is a 30-second brand film or a long-form narrative, the centre remains the same: a story that feels emotionally grounded, culturally awake, and formally precise.', 310, 'about', 'hero', 'lead'),
('about.panel1.heading', 'Why we exist', 40, 'about', 'panel1', 'heading'),
('about.panel1.body', 'SARVSHIVAM holds space for image, sound, and meaning to arrive in the same frame. The work does not chase volume. It seeks resonance. A clean emotional line. A point of view that lingers after the screen goes dark.', 200, 'about', 'panel1', 'body'),
('about.panel1.list.1', 'Brand communication with narrative depth.', 100, 'about', 'panel1', 'list-item'),
('about.panel1.list.2', 'Cultural intelligence without spectacle.', 100, 'about', 'panel1', 'list-item'),
('about.panel1.list.3', 'Minimal form with cinematic weight.', 100, 'about', 'panel1', 'list-item'),
('about.panel2.heading', 'What grounds the work', 40, 'about', 'panel2', 'heading'),
('about.panel2.body', 'Intent is a discipline. Before pace, before format, before platform, there is clarity. What is this film really holding? What does it want the viewer to feel? What remains when noise dissolves?', 200, 'about', 'panel2', 'body'),
('about.panel2.list.1', 'Presence over excess.', 100, 'about', 'panel2', 'list-item'),
('about.panel2.list.2', 'Meaning over novelty.', 100, 'about', 'panel2', 'list-item'),
('about.panel2.list.3', 'Precision over clutter.', 100, 'about', 'panel2', 'list-item'),
('about.pillars.eyebrow', 'Three Pillars', 30, 'about', 'pillars', 'eyebrow'),
('about.card1.heading', 'Story', 30, 'about', 'card1', 'heading'),
('about.card1.body', 'Every frame must move the internal arc forward. Atmosphere matters, but it must serve narrative.', 150, 'about', 'card1', 'body'),
('about.card2.heading', 'Culture', 30, 'about', 'card2', 'heading'),
('about.card2.body', 'Identity is not costume here. It is texture, memory, rhythm, language, and ethical location.', 150, 'about', 'card2', 'body'),
('about.card3.heading', 'Intent', 30, 'about', 'card3', 'heading'),
('about.card3.body', 'Form follows inner clarity. When the intent is honest, the visual language becomes inevitable.', 150, 'about', 'card3', 'body'),
('about.footer.left', 'Films for brands. Stories for the future.', 60, 'about', 'footer', 'text'),

('work.marker', 'दृष्टि', 15, 'work', 'marker', 'devanagari'),
('work.hero.eyebrow', 'Work Library', 30, 'work', 'hero', 'eyebrow'),
('work.hero.title', 'A glimpse of the world we build.', 50, 'work', 'hero', 'title'),
('work.hero.lead', 'Narrative-driven films for platforms, brands, and moving-image identities. Every frame is intentional. Every story is clean, clear, and emotionally grounded.', 310, 'work', 'hero', 'lead'),
('work.footer.left', 'Every frame is intentional.', 60, 'work', 'footer', 'text'),
('work.filter.all', 'All', 15, 'work', 'filters', 'button'),
('work.filter.short', 'Short Film', 15, 'work', 'filters', 'button'),
('work.filter.music', 'Music Video', 15, 'work', 'filters', 'button'),
('work.filter.brand', 'Brand Film', 15, 'work', 'filters', 'button'),

('narrative.marker', 'आगे', 15, 'narrative', 'marker', 'devanagari'),
('narrative.hero.eyebrow', 'Narrative & Originals', 30, 'narrative', 'hero', 'eyebrow'),
('narrative.hero.title', 'The future we are building toward.', 50, 'narrative', 'hero', 'title'),
('narrative.hero.lead', 'Short films, concepts, and long-form narratives in development. This is where SARVSHIVAM moves when the brief ends and the inner voice continues. Presence over volume. Direction over noise.', 310, 'narrative', 'hero', 'lead'),
('narrative.progress1.label', 'Feature concept — mythology / memory', 40, 'narrative', 'progress', 'label'),
('narrative.progress2.label', 'Short narrative — urban solitude', 40, 'narrative', 'progress', 'label'),
('narrative.progress3.label', 'Essay film — culture / body / ritual', 40, 'narrative', 'progress', 'label'),
('narrative.ring.text', 'POINT OF VIEW', 20, 'narrative', 'ring', 'text'),
('narrative.card1.heading', 'Long-form', 30, 'narrative', 'card1', 'heading'),
('narrative.card1.body', 'Stories that can hold contradiction without flattening it. Character first. Atmosphere in service of arc.', 150, 'narrative', 'card1', 'body'),
('narrative.card2.heading', 'Original IP', 30, 'narrative', 'card2', 'heading'),
('narrative.card2.body', 'Worlds emerging from cultural memory, physical discipline, identity, and spiritual tension.', 150, 'narrative', 'card2', 'body'),
('narrative.card3.heading', 'Future collaborations', 30, 'narrative', 'card3', 'heading'),
('narrative.card3.body', 'Selective partnerships with producers, studios, and platforms aligned with depth, patience, and craft.', 150, 'narrative', 'card3', 'body'),
('narrative.footer.left', 'This is where intent turns into point of view.', 60, 'narrative', 'footer', 'text'),

('founder.marker', 'उपस्थिति', 15, 'founder', 'marker', 'devanagari'),
('founder.hero.eyebrow', 'Founder Presence', 30, 'founder', 'hero', 'eyebrow'),
('founder.hero.title', 'Bhavya Attrey', 50, 'founder', 'hero', 'title'),
('founder.hero.lead', 'Filmmaker. Storyteller. Strength & Conditioning Coach. Student of Hindu Studies. Cricketer. Working at the intersection of culture, performance, and cinematic expression.', 310, 'founder', 'hero', 'lead'),
('founder.panel.heading', 'The hand behind the vision', 40, 'founder', 'panel', 'heading'),
('founder.panel.body', 'The studio language comes from lived texture — discipline, observation, body, memory, and the ability to sit with silence long enough for the real thing to arrive. The founder page is not a pedestal. It is context.', 200, 'founder', 'panel', 'body'),
('founder.bio.list.1', 'Sees storytelling as embodied practice.', 100, 'founder', 'bio', 'list-item'),
('founder.bio.list.2', 'Works across commercial briefs and original narrative development.', 100, 'founder', 'bio', 'list-item'),
('founder.bio.list.3', 'Draws from cultural inquiry without reducing it to surface signals.', 100, 'founder', 'bio', 'list-item'),
('founder.bio.list.4', 'Builds visual environments that feel composed, not crowded.', 100, 'founder', 'bio', 'list-item'),
('founder.bio.list.5', 'Leads with restraint, then lets the image speak.', 100, 'founder', 'bio', 'list-item'),

('contact.marker', 'शिवम्', 15, 'contact', 'marker', 'devanagari'),
('contact.hero.eyebrow', 'Contact', 30, 'contact', 'hero', 'eyebrow'),
('contact.hero.title', 'Let''s create something that matters.', 50, 'contact', 'hero', 'title'),
('contact.hero.lead', 'If the project needs clarity, emotional precision, and a cinematic point of view, start the conversation. The invitation is open.', 310, 'contact', 'hero', 'lead'),
('contact.channel1.label', 'Email', 15, 'contact', 'channel1', 'label'),
('contact.channel1.value', 'hello@sarvshivamfilms.com', 50, 'contact', 'channel1', 'value'),
('contact.channel2.label', 'Instagram', 15, 'contact', 'channel2', 'label'),
('contact.channel2.value', '@sarvshivamfilms', 50, 'contact', 'channel2', 'value'),
('contact.channel3.label', 'Vimeo', 15, 'contact', 'channel3', 'label'),
('contact.channel3.value', 'vimeo.com/sarvshivamfilms', 50, 'contact', 'channel3', 'value'),
('contact.channel4.label', 'YouTube', 15, 'contact', 'channel4', 'label'),
('contact.channel4.value', 'youtube.com/@sarvshivamfilms', 50, 'contact', 'channel4', 'value'),
('contact.quote.body', 'Creation begins in silence. Then shape arrives. Then rhythm. Then the frame remembers what it was always trying to become.', 250, 'contact', 'quote', 'body'),
('contact.quote.muted', 'For commissions, collaborations, brand films, and narrative development conversations.', 250, 'contact', 'quote', 'muted'),
('contact.footer.left', 'Creation begins in silence.', 60, 'contact', 'footer', 'text'),

('shared.nav.home', 'Home', 15, 'shared', 'nav', 'nav-link'),
('shared.nav.intent', 'Intent', 15, 'shared', 'nav', 'nav-link'),
('shared.nav.work', 'Work', 15, 'shared', 'nav', 'nav-link'),
('shared.nav.narrative', 'Narrative', 15, 'shared', 'nav', 'nav-link'),
('shared.nav.founder', 'Founder', 15, 'shared', 'nav', 'nav-link'),
('shared.nav.contact', 'Contact', 15, 'shared', 'nav', 'nav-link'),
('shared.nav.admin', 'Admin', 15, 'shared', 'nav', 'nav-link'),

('shared.footer.devanagari', 'सर्व शिवमयम्', 30, 'shared', 'footer', 'devanagari');